[versions]
app-version = "1.0.0"
boot = "3.5.7"
dm = "1.1.7"
jackson-xml = "3.0.1"

[libraries]
jackson-dataformat-xml = { module = "tools.jackson.dataformat:jackson-dataformat-xml", version.ref = "jackson-xml" }
